export const animals = [
  { name: 'Alan',       animal: 'Anteater', id: 10, role: 'admin' },
  { name: 'Bobby',      animal: 'Badger',   id: 20, role: 'admin' },
  { name: 'Brenda',     animal: 'Badger',   id: 30, role: 'admin' },
  { name: 'Christina',  animal: 'Cat',      id: 40, role: 'user'  },
  { name: 'Derek',      animal: 'Dog',      id: 50, role: 'user'  },
  { name: 'Delia',      animal: 'Donkey',   id: 60, role: 'admin' },
  { name: 'Edwin',      animal: 'Elephant', id: 70, role: 'admin' },
  { name: 'Frank',      animal: 'Ferret',   id: 80, role: 'user'  },
  { name: 'Felicity',   animal: 'Fox',      id: 90, role: 'admin' },
  { name: 'Gertrude',   animal: 'Goat',     id: 11, role: 'admin' },
  { name: 'Hector',     animal: 'Hamster',  id: 12, role: 'admin' },
  { name: 'Ian',        animal: 'Iguana',   id: 13, role: 'user'  },
  { name: 'Julie',      animal: 'Jellyfish',id: 14, role: 'user'  },
  { name: 'Kevin',      animal: 'Koala',    id: 21, role: 'user'  },
  { name: 'Lionel',     animal: 'Llama',    id: 22, role: 'user'  },
  { name: 'Mary',       animal: 'Magpie',   id: 23, role: 'user'  },
  { name: 'Nerys',      animal: 'Narwhal',  id: 24, role: 'user'  },
  { name: 'Oliver',     animal: 'Octopus',  id: 31, role: 'user'  },
  { name: 'Penny',      animal: 'Panda',    id: 32, role: 'admin' },
  { name: 'Quentin',    animal: 'Quail',    id: 33, role: 'admin' },
  { name: 'Roger',      animal: 'Raccoon',  id: 41, role: 'user'  },
  { name: 'Simon',      animal: 'Stoat',    id: 42, role: 'user'  },
  { name: 'Terry',      animal: 'Tiger',    id: 43, role: 'user'  },
  { name: 'Ursula',     animal: 'Unicorn',  id: 51, role: 'user'  },
  { name: 'Violet',     animal: 'Vole',     id: 52, role: 'user'  },
  { name: 'Willy',      animal: 'Wombat',   id: 53, role: 'user'  },
  { name: 'Xerces',     animal: 'Xenus',    id: 61, role: 'user'  },
  { name: 'Yvonne',     animal: 'Yaz',      id: 62, role: 'user'  },
  { name: 'Zebedee',    animal: 'Zebra',    id: 63, role: 'user'  }
]
