export const SELECT_CLASS               = 'select'
export const SELECT_PLACEHOLDER         = 'Select'
export const SELECT_SUFFIX_ICON         = 'angle-down'
export const SELECT_SEARCH_PLACEHOLDER  = 'Search'
export const SELECT_SEARCH_FIELD_CLASS  = 'search field'
export const SELECT_SEARCH_PREFIX_CLASS = 'shaded lined prefix'
export const SELECT_SEARCH_SUFFIX_CLASS = 'shaded lined suffix'
