export const DASH       = '-'
export const BLANK      = ''
export const ARROW_DOWN = 'ArrowDown'
export const ARROW_UP   = 'ArrowUp'
export const TAB        = 'Tab'
export const ENTER      = 'Enter'
export const SPACE      = ' '
export const ESCAPE     = 'Escape'
export const BACKSPACE  = 'Backspace'
export const DEFAULT_ICON_WIDTH  = 512
export const DEFAULT_ICON_HEIGHT = 512
